### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [pierredarrieutort/fitext#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by pierredarrieutort** [comment]
Hi, Geopic !

Thanks you for your interest, if you want you can do pull request on the project 😉 .
I don't used to deal with TypeScript, it will need to implement in the npm package then ?

**Comment by geopic** [comment]
Thanks @pierredarrieutort, as for your question I don't think I will need to install any extra packages but I would need to add a `types` entry to `package.json`. I'll get started on it now :smile:

**Comment by pierredarrieutort** [comment]
I've merge your PR, thanks you for you contribution ;)
