### ISSUE TITLE
Infinite loop when trying reducing the height of the fitter container to the minimum

### ISSUE THREAD

**Issue by maelquerre** [pierredarrieutort/fitext#5]
## Expected behaviour

The font size should reduce to the very least (even if not even visible I guess?) when extremely reducing the height of a container.

## Actual behaviour

The website stops responding. From what I could notice, this is probably due to an infinite loop trying to update the children font sizes while it's still overflowing...

## How to reproduce

Go to the [project's demo](https://pierredarrieutort.github.io/fitext/) and try reducing the height to the minimum (it get stuck around a height of 20% (for a width of 60%) if your doing it slowly, but the values don't matter much, it's rather the action of reducing the height to its minimum).

## Specifications (just in case)

- Version: fitext v1.0.5
- Browser: Google Chrome 81.0.4044.138
- OS: macOS 10.12.6

**Comment by pierredarrieutort** [comment]
Thanks you for your feedback !
I've fixed it, it will be patched in the next package update 😉.
